### ISSUE TITLE
ip2location_latitude and ip2location_longitude strips decimals

### ISSUE THREAD

**Issue by tjegan** [chaizhenhua/ngx-ip2location#4]
ip2location_latitude and ip2location_longitude are not showing the full value with decimals.
It strips the decimals.

**Comment by chaizhenhua** [comment]
hi @tjegan , thanks for your report. could you show me some example value of ip2location_longitude?

**Comment by tjegan** [comment]
For example, The latitude and longitude of IP 115.111.23.215 should be 12.976230 and 77.603290 but ngx-ip2location returns 12 and 77 where as the ip2location database has value of 12.976230, 77.603290

**Comment by chaizhenhua** [comment]
Hi @tjegan . This has been fixed here 978e652d5cc859deb2d9142efcfe4a77d0f06b5d.

**Comment by tjegan** [comment]
Thanks! It works as expected.
