### ISSUE TITLE
Installed but not using the variables

### ISSUE THREAD

**Issue by bertalanimre** [chaizhenhua/ngx-ip2location#5]
Hey Chaizhenhua!

Thanks for the great module for NginX. However I can't use it somewhy. 
After make && make install I've added to the config:
html {
....
ip2location_database /home/NginX/database-ip2loc/IP2LOCATION-LITE-DB1.BIN;  
add_header CC $ip2location_country_code;
add_header CN $ip2location_country_name;
...
    server {
...
location / {
...
if ( $ip2location_country_code = "HU" ) {return 403;}
}
...etc

The index.php shows me correctly and I don't get the 403 error nor any other error. 

I saw a Module Configuration part in your guide, can you axplain that part a bit more detailed please? Did I skip that part?

Cheers!
Bert

**Comment by bertalanimre** [comment]
Partly my bad, I've forgot the example file. But now whenever I want to run nginx it gives the following error:
nginx: [emerg] unknown directive "ip2location" in /usr/local/nginx/conf/nginx.conf:15

Any idea?

**Comment by bertalanimre** [comment]
Again helping myself. :) I've recompiled again from scratch, somehow now the above perrors are gone. Now, the only issue is that with the example index.php I get strange values only:
COUNTRY_SHORT => "-"
COUNTRY_LONG => "-"
REGION => ""
CITY => ""
ISP => "0.000000"
LATITUDE => "0.000000"
LONGITUDE => ""
DOMAIN => ""
ZIPCODE => ""
TIMEZONE => ""
NETSPEED => ""
IDDCODE => ""
AREACODE => ""
WEATHERSTATIONCODE => ""
WEATHERSTATIONNAME => ""
MCC => ""
MNC => ""
MOBILEBRAND => ""
ELEVATION => "0.000000"
USAGETYPE => ""

**Comment by tjegan** [comment]
You should pass the ip2location variables to PHP in your virtual hosts  .php location settings.
And you are using the wrong variable in your condition to block countries.
It should be $ip2location_country_short instead of $ip2location_country_code

**Comment by bertalanimre** [comment]
Sorted it out. It was mainly local issue. The NginX recieved out firewalls IP address that looks like 10.X.X.X. OFC this isn't in the database. :D When I've installed it on a VPS in the outsideworld it worked. So sorry for giving an issue. :) :+1:

**Comment by chaizhenhua** [comment]
@bertalanimre  sorry for reply so late. did you resolved the TOO_MANY_REDIRECTS error?

**Comment by bertalanimre** [comment]
Yes, I did. Thank you.
